name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Maven
      run: sudo apt-get install maven
    - name: Build with Maven
      run: mvn -B package
    - name: Set up Appium
      run: |
        sudo apt-get update
        sudo apt-get install -y libappium-java-client-java
        sudo apt-get install -y openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
    - name: Set up Android Driver
      run: |
        sudo apt-get install -y unzip
        wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
    - name: Test with Appium
      run: |
        Xvfb :99 -ac &
        export DISPLAY=:99
        mvn -B test -Dtest=AppTests
